services:
  mysql:
    image: 'mysql:8.3.0'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  libretranslate:
    image: 'libretranslate/libretranslate:latest'
    ports:
      - '5000:5000'
