services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=springLabDb'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
      - 'MYSQL_USER=root'
    ports:
      - '3306:3306'
